[attributes]
1  = { name = "User-Name", type = "string" }
2  = { name = "User-Password", type = "octets" }
3  = { name = "CHAP-Password", type = "octets" }
4  = { name = "NAS-IP-Address", type = "ipaddr" }
5  = { name = "NAS-Port", type = "integer" }
6  = { name = "Service-Type", type = "integer" }
7  = { name = "Framed-Protocol", type = "integer" }
8  = { name = "Framed-IP-Address", type = "ipaddr" }
11 = { name = "Filter-Id", type = "string" }
25 = { name = "Class", type = "octets" }
26 = { name = "Vendor-Specific", type = "octets" }
27 = { name = "Session-Timeout", type = "integer" }
28 = { name = "Idle-Timeout", type = "integer" }
30 = { name = "Called-Station-Id", type = "string" }
31 = { name = "Calling-Station-Id", type = "string" }
32 = { name = "NAS-Identifier", type = "string" }
40 = { name = "Acct-Status-Type", type = "integer", enums = { 1 = "Start", 2 = "Stop", 3 = "Interim-Update", 4 = "On", 5 = "Off" } }
41 = { name = "Acct-Delay-Time", type = "integer" }
42 = { name = "Acct-Input-Octets", type = "integer" }
43 = { name = "Acct-Output-Octets", type = "integer" }
44 = { name = "Acct-Session-Id", type = "string" }
45 = { name = "Acct-Authentic", type = "integer" }
46 = { name = "Acct-Session-Time", type = "integer" }
47 = { name = "Acct-Input-Packets", type = "integer" }
48 = { name = "Acct-Output-Packets", type = "integer" }
49 = { name = "Acct-Terminate-Cause", type = "integer", enums = { 1 = "User-Request", 2 = "Lost-Carrier", 3 = "Lost-Service", 4 = "Idle-Timeout", 5 = "Session-Timeout", 6 = "Admin-Reset", 7 = "Admin-Reboot", 8 = "Port-Error", 9 = "NAS-Error", 10 = "NAS-Request", 11 = "NAS-Reboot", 12 = "Port-Unneeded", 13 = "Port-Preempted", 14 = "Port-Suspended", 15 = "Service-Unavailable", 16 = "Callback", 17 = "User-Error", 18 = "Host-Request" } }
50 = { name = "Acct-Multi-Session-Id", type = "string" }
51 = { name = "Acct-Link-Count", type = "integer" }
52 = { name = "Acct-Input-Gigawords", type = "integer" }
53 = { name = "Acct-Output-Gigawords", type = "integer" }
60 = { name = "CHAP-Challenge", type = "octets" }
61 = { name = "NAS-Port-Type", type = "integer", enums = { 0 = "Async", 1 = "Sync", 2 = "ISDN-Sync", 3 = "ISDN-Async-V.120", 4 = "ISDN-Async-V.110", 5 = "Virtual", 6 = "PIAFS", 7 = "HDLC-Clear-Channel", 8 = "X.25", 9 = "X.75", 10 = "G.3-Fax", 11 = "SDSL", 12 = "ADSL-CAP", 13 = "ADSL-DMT", 14 = "IDSL", 15 = "Ethernet", 16 = "xDSL", 17 = "Cable", 18 = "Wireless-Other", 19 = "Wireless-802.11" } }
80 = { name = "Message-Authenticator", type = "octets" }
87 = { name = "NAS-Port-Id", type = "string" }

# Vendor definitions
[vendors]

[vendors.14988]
name = "Mikrotik"
[vendors.14988.attributes]
1  = { name = "Mikrotik-Recv-Limit", type = "integer" }
2  = { name = "Mikrotik-Xmit-Limit", type = "integer" }
3  = { name = "Mikrotik-Group", type = "string" }
8  = { name = "Mikrotik-Rate-Limit", type = "string" }
9  = { name = "Mikrotik-Realm", type = "string" }
10 = { name = "Mikrotik-Host-IP", type = "ipaddr" }
11 = { name = "Mikrotik-Mark-Id", type = "string" }
12 = { name = "Mikrotik-Advertise-URL", type = "string" }
13 = { name = "Mikrotik-Advertise-Interval", type = "integer" }
14 = { name = "Mikrotik-Recv-Limit-Gigawords", type = "integer" }
15 = { name = "Mikrotik-Xmit-Limit-Gigawords", type = "integer" }
17 = { name = "Mikrotik-Total-Limit", type = "integer" }
18 = { name = "Mikrotik-Total-Limit-Gigawords", type = "integer" }
19 = { name = "Mikrotik-Address-List", type = "string" }
22 = { name = "Mikrotik-Delegated-IPv6-Pool", type = "string" }
26 = { name = "Mikrotik-Wireless-VLANID", type = "integer" }
