name: Radclient Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  radclient:
    env:
      RUSTFLAGS: "-D warnings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install radclient
        run: |
          sudo apt-get update
          sudo apt-get install -y freeradius-utils

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Run radclient integration tests
        run: scripts/radclient-tests.sh
